services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq-local"
    ports:
      - 5672:5672
    networks:
      - default
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 5s
        timeout: 10s
        retries: 10
  gateway:
    image: evgenyarbatov/api-gateway
    container_name: "api-gateway"
    ports:
      - 8080:8080 
    environment:
        - AMQP_URL=${AMQP_URL}
    networks:
      - default
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  default:
    driver: bridge
