services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq-local"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3
  gateway:
    image: evgenyarbatov/api-gateway
    container_name: "api-gateway"
    ports:
      - 8080:8080 
    environment:
      - AMQP_URL=amqp://rabbitmq
      - QUEUE_NAME=api
      - GATEWAY_PORT=8080
    networks:
      - default
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  default:
    driver: bridge
