services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - 5672:5672
    networks:
      - default
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
  gateway:
    image: evgenyarbatov/api-gateway
    container_name: "api-gateway"
    ports:
      - 8080:8080 
    environment:
        - AMQP_URL=${AMQP_URL}
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - rabbitmq

networks:
  default:
    driver: bridge
