services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq-remote"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 1s
        timeout: 3s
        retries: 30
  consumer:
    image: evgenyarbatov/rabbitmq-consumer
    container_name: "rabbitmq-consumer"
    environment:
        - AMQP_URL=${AMQP_URL}
        - SERVER_URL=${SERVER_URL}
    networks:
      - default
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
  server:
    image: evgenyarbatov/api-server
    container_name: "api-server"
    ports:
      - 9090:9090
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
