services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq-remote"
    ports:
      - 5672:5672
    networks:
      - default
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
  consumer:
    image: evgenyarbatov/rabbitmq-consumer
    container_name: "rabbitmq-consumer"
    environment:
        - AMQP_URL=${AMQP_URL}
        - SERVER_URL=${SERVER_URL}
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - rabbitmq
  server:
    image: evgenyarbatov/api-server
    container_name: "api-server"
    ports:
      - 9090:9090 
    environment:
        - AMQP_URL=${AMQP_URL}
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - consumer

networks:
  default:
    driver: bridge
